### ISSUE TITLE
Add to aur

### ISSUE THREAD

**Issue by Ashark** [fanzhuyifan/kwin-effect-reflect-cursor#1]
Hello. Today the kwin 6.2 arrived to Arch Linux. So it is possible to have this effect in aur.

I created the following draft of the PKGBUILD:
```bash
# Maintainer: ... <>

_reponame=kwin-effect-reflect-cursor
pkgname=kwin-effects-reflect-cursor-git
pkgver=1  # todo
pkgrel=1
pkgdesc="Reflects the cursor near screen edges to make it more visible"
arch=(x86_64)
url="https://github.com/fanzhuyifan/kwin-effect-reflect-cursor"
license=(GPL3)
depends=()  # todo
makedepends=(extra-cmake-modules)  # todo
source=("git+https://github.com/fanzhuyifan/kwin-effect-reflect-cursor")
sha256sums=("SKIP")

prepare() {
  mkdir -p build
}

build() {
    cmake -B build -S "$_reponame" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    cmake --build build
}

package() {
    DESTDIR="$pkgdir" cmake --install build
}

```

Built it, relogined, activated in settings, and it works. Thank you!

Are you willing to create an aur package?

**Comment by fanzhuyifan** [comment]
Thanks for the reminder! Uploaded to https://aur.archlinux.org/packages/kwin-effect-reflect-cursor-git

**Comment by Ashark** [comment]
Thanks. But I think the "correct" package name would be "kwin-effect**S**-...", no?

**Comment by fanzhuyifan** [comment]
> Thanks. But I think the "correct" package name would be "kwin-effect**S**-...", no?

Ooops I didn't notice that. Currently 4 other packages are named "kwin-effect-", including the one with the most votes [0], so I am just going to let it be for now... 

[0] https://aur.archlinux.org/packages?O=0&K=kwin+effect

**Comment by Ashark** [comment]
Ok, let it be as it is now. For the note, I created a discussion in archwiki so we would have a guideline for that. See [here](https://wiki.archlinux.org/title/Talk:KDE_package_guidelines#Specify_other_kde_related_packages_naming_convention).
